import dotenv from 'dotenv';
dotenv.config();
export const DBHOST = process.env.DBHOST ?? 'localhost';
export const DBPORT = process.env.DBPORT ?? 27017;
export const DATABASE = process.env.DATABASE ?? 'book_store_app';
export const PORT = process.env.PORT ?? 9090;
export const PASSWORDSALT = parseInt(process.env.PASSWORDSALT) ?? 10;
export const TOKENEXPIRETIME = process.env.TOKENEXPIRETIME ?? '1h';
export const SECRET = process.env.SECRET ?? 'booksecret_($%#@$%store@123Application))';
export const SALT = parseInt(process.env.SALT) ?? 10;
export const ADMINUSERNAME = process.env.ADMINUSERNAME ?? 'magadhtech';
export const ADMINUSERPASSWORD = process.env.ADMINUSERPASSWORD ?? 'Magadh@12';
export const ADMINUSEREMAIL = process.env.ADMINUSEREMAIL ?? "accounts@magadh.tech";
export const QUEUENAME = process.env.QUEUENAME ?? "bookstore";
export const FROMEMAIL = process.env.FROMEMAIL ?? "support@noreply.com";
export const GMAILFORNODEMAILER = process.env.GMAILFORNODEMAILER;
export const PASSWORDFORNODEMAILER = process.env.PASSWORDFORNODEMAILER;
export const NODEMAILERPORT = process.env.NODEMAILERPORT;
export const DATEOFMONTH = process.env.DATEOFMONTH ?? '28-31';
export const TIMEOFSCHEDULE = process.env.TIMEOFSCHEDULE ?? '23';
